--1. what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS total_purchase_amount
FROM customers
GROUP BY gender;

--2. which customers used discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customers
WHERE purchase_amount>(SELECT ROUND(AVG(purchase_amount),2)
						FROM customers) AND discount_applied='Yes'
GROUP BY customer_id, purchase_amount
LIMIT 10;
--3. which is the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating)::numeric,2)AS average_review
FROM customers
GROUP BY item_purchased
ORDER BY average_review DESC
LIMIT 5;
--4. compare the average purchase amounts among Store Pickup stardard and express shipping
SELECT shipping_type,ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM customers
WHERE shipping_type IN('Standard','Express','Store Pickup')
GROUP BY shipping_type
ORDER BY average_purchase_amount DESC;
--5. do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, count(*) AS total_customers,
		ROUND(AVG(purchase_amount),2)AS avarage_revenue,
		SUM(purchase_amount)AS total_revenue
FROM customers
GROUP BY subscription_status;
--6. which 5 products have the highest percentage of purchases with discount applied
SELECT item_purchased,ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2)AS percent_of_purchases_on_discount
FROM customers
GROUP BY item_purchased
ORDER BY percent_of_purchases_on_discount DESC
LIMIT 5;
--7. which 5 products have the highest percentage of purchases without discount applied
SELECT item_purchased,ROUND(100*SUM(CASE WHEN discount_applied='No' THEN 1 ELSE 0 END)/COUNT(*),2)AS percent_of_purchases_without_discount
FROM customers
GROUP BY item_purchased
ORDER BY percent_of_purchases_without_discount DESC
LIMIT 5;
--OR
SELECT item_purchased,ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2)AS percent_of_purchases_on_discount
FROM customers
GROUP BY item_purchased
ORDER BY percent_of_purchases_on_discount 
LIMIT 5;
--8. segment customers into new, returning and loyal based on their total number of previous purchases and show the count of each segment
WITH customer_type AS(SELECT customer_id,previous_purchases,
			CASE 
				WHEN previous_purchases<=5 THEN 'New'
				WHEN previous_purchases BETWEEN 6 AND 20 THEN 'Returning'
				ELSE 'Loyal' 
				END AS customer_segment
				FROM customers)
SELECT customer_segment,COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;
		

--9. what are the top 3 most purchased products in each category?
WITH product_counts AS(
SELECT category, item_purchased,
COUNT(customer_id)AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id)DESC)AS product_rank
FROM customers
GROUP BY category,item_purchased)

SELECT product_rank, category,item_purchased,total_orders
FROM product_counts
WHERE product_rank<=3;

--10. are customers who are repeat buyers( more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,COUNT(*)as repeat_customers
FROM customers
WHERE previous_purchases>5
GROUP BY subscription_status
--11. what is the revenue contribution of each age group?
SELECT age_group,SUM(purchase_amount) AS total_revenue_contri
FROM customers
GROUP BY age_group
ORDER BY total_revenue_contri DESC;
--12 how many females and males are subscribed and not subscribed
SELECT gender , subscription_status,COUNT(*)AS total_by_gender
FROM customers
GROUP BY gender, subscription_status;

